from typing import Literal

ROLE_ADMIN = "admin"
ROLE_MERCHANDISER = "merchandiser"
ROLE_MERCHANDISER_PRO = "merchandiser-pro"
ROLE_ENTERPRISE = "enterprise"

VALID_ROLES = [ROLE_ADMIN, ROLE_MERCHANDISER, ROLE_MERCHANDISER_PRO, ROLE_ENTERPRISE]
ROLE_TYPE = Literal["admin", "merchandiser", "merchandiser-pro", "enterprise"]

TIER_ADMIN = "admin"
TIER_INDIVIDUAL_PLUS = "individual-plus"
TIER_INDIVIDUAL_PRO = "individual-pro"
TIER_ENTERPRISE = "enterprise"

VALID_TIERS = [TIER_ADMIN, TIER_INDIVIDUAL_PLUS, TIER_INDIVIDUAL_PRO, TIER_ENTERPRISE]
TIER_TYPE = Literal["admin", "individual-plus", "individual-pro", "enterprise"]

LOGIN_MODE_ADMIN = "admin"
LOGIN_MODE_INDIVIDUAL_PLUS = "individual plus"
LOGIN_MODE_INDIVIDUAL_PRO = "individual pro"
LOGIN_MODE_ENTERPRISE = "enterprise"

VALID_LOGIN_MODES = [
    LOGIN_MODE_ADMIN,
    LOGIN_MODE_INDIVIDUAL_PLUS,
    LOGIN_MODE_INDIVIDUAL_PRO,
    LOGIN_MODE_ENTERPRISE,
]
LOGIN_MODE_TYPE = Literal["admin", "individual plus", "individual pro", "enterprise"]

ROLE_TO_DEFAULT_TIER = {
    ROLE_ADMIN: TIER_ADMIN,
    ROLE_MERCHANDISER: TIER_INDIVIDUAL_PLUS,
    ROLE_MERCHANDISER_PRO: TIER_INDIVIDUAL_PRO,
    ROLE_ENTERPRISE: TIER_ENTERPRISE,
}

LOGIN_MODE_TO_ROLE_TIER = {
    LOGIN_MODE_ADMIN: (ROLE_ADMIN, TIER_ADMIN),
    LOGIN_MODE_INDIVIDUAL_PLUS: (ROLE_MERCHANDISER, TIER_INDIVIDUAL_PLUS),
    LOGIN_MODE_INDIVIDUAL_PRO: (ROLE_MERCHANDISER_PRO, TIER_INDIVIDUAL_PRO),
    LOGIN_MODE_ENTERPRISE: (ROLE_ENTERPRISE, TIER_ENTERPRISE),
}

DEFAULT_PLAN_LIMITS = {
    TIER_ADMIN: None,
    TIER_INDIVIDUAL_PLUS: 15,
    TIER_INDIVIDUAL_PRO: 45,
    TIER_ENTERPRISE: None,
}

ERROR_CODE_QUOTA_EXCEEDED = "quota_exceeded"
ERROR_CODE_INVALID_CREDENTIALS = "invalid_credentials"
ERROR_CODE_EMAIL_EXISTS = "email_exists"
ERROR_CODE_ACCOUNT_TYPE_MISMATCH = "account_type_mismatch"
ERROR_CODE_UNAUTHORIZED = "unauthorized"
ERROR_CODE_FORBIDDEN = "forbidden"